config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
#  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :new_topic_alert
  resources :new_comment_response
   resources :topics  do
    resources :comments
   end
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :name, presence: true,
                    length: { minimum: 3 }

  validates :title, presence: true,
                    length: { minimum: 5 }


 def self.listings
     @listings = ["Angie","Clare","Debbie","Helen","Sarah","Vicky","David","Mike","Howard"]
  end
  def self.votings
    @votings = [Angie_vote,Clare_vote,Debbie_vote,Helen_vote,Sarah_vote,Vicky_vote,David_vote,Mike_vote,Howard_vote]
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

   def send_alert(topic)
     @topic = Topic.new(topic_params)
     users = User.all
     users.each do |u|
       UserMailer.new_topic_alert(@topic, u).deliver_now
     end
   end

   def index
    @topics = Topic.all.sort_by {|obj| obj.created_at }.reverse
    @votes=["Not Voted", "For", "Against", "Undecided", "N/a" ]
  end

  def show
    @topic = Topic.find(params[:id])
    @votes=["Not Voted", "For", "Against", "Undecided", "N/a" ]
  end

  def new
    @topic = Topic.new
    @votes=["Not Voted", "For", "Against", "Undecided", "N/a" ]
  end

  def edit
    @topic = Topic.find(params[:id])
    @votes=["Not Voted", "For", "Against", "Undecided", "N/a" ]
  end

   def create
    @topic = Topic.new(topic_params)
    if @topic.save
       send_alert(@topic)
       flash[:info] = "New Topic alert emails sent."
       redirect_to root_url
    else
     render 'new'
    end
  end

  def update
    @topic = Topic.find(params[:id])

    if @topic.update(topic_params)
      redirect_to @topic
    else
      render 'edit'
    end
  end
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    redirect_to topics_path
  end

  private
    def topic_params
      params.require(:topic).permit(:name, :title, :proposal,:"#{current_user.name}_vote".to_sym)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_choices.html.erb
<select name=#{current_user.name}_vote">
      <%= @votes.each do |vote| %>
        <option value="<%= vote %>"><%= vote %></option>
      <% end %>
    </select>

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@topic.errors.count, "error") %> prohibited
        this proposal from being saved:
      </h2>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
</p>
     <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, :value => current_user.name  %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :proposal %><br>
    <%= f.text_area :proposal %>
  </p>

  <p>
<!--    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %> -->
  </p>
<h2 style="color:red;"> Register your Vote</h2>
<p>
  Please vote on your proposal by selecting "For, Against, Undecided or N/a
   ( for cases where a vote is not appropriate)".  Then click the submit button.
</p>
<p>
  This is the best place for the proposer to vote, other members will be asked
   to do so elsewhere.
</p>
   <p>
    <div style='width: 400px; margin: auto'><%=f.label :"#{current_user.name}_vote".to_sym%></div>
    <div style='width: 200px; margin: auto'><%=f.select  "#{current_user.name}_vote".to_sym, options_for_select(@votes) %></div>
  </p>
<p>
    <div style='width: 400px; margin: auto'><%= f.submit "Submit Proposal & Vote", class: "btn btn-primary btn-lg" %></div>
</p>
<%end%>

app/views/topics/edit.html.erb
<h1>Editing Proposal</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing Proposals</h1>
<%= link_to 'Submit New Proposal', new_topic_path %>
<style>
table, th, td, tr {
    border: 1px solid red;
}
th, td {
    padding: 5px;
}
</style>

<%if !current_user.admin%>

  <table style= "width:80%; margin:auto;">
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Date</th>
    <th colspan="3"></th>
  </tr>

  <% @topics.each do |topic| %>
    <tr>
      <td style="vertical-align:text-top;"><%= topic.name %></td>
      <td style="vertical-align:text-top;"><%= topic.title %></td>
      <td><%= topic.created_at.strftime("%d:%m:%Y") %></td>
      <td style="vertical-align:text-top;"><%= link_to 'Show', topic_path(topic) %></td>

    </tr>
    <%end%>
  </table>
  <%else%>

    <table style= "width:80%; margin:auto;">
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>

    <% @topics.each do |topic| %>
    <tr>
      <td style="vertical-align:text-top;"><%= topic.name %></td>
      <td style="vertical-align:text-top;"><%= topic.title %></td>
      <td><%= topic.created_at.strftime("%d:%m:%Y") %></td>
      <td style="vertical-align:text-top;"><%= link_to 'Show', topic_path(topic) %></td>
      <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
      <td><%= link_to 'Destroy', topic_path(topic),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <%end%>
   </table>
<%end%>

app/views/topics/new.html.erb
<h3> New Committee Proposal</h3>
<%= render 'form' %>
<!--<%= link_to 'Back', topics_path %>-->

app/views/topics/show.html.erb
<h1>Proposal</h1>
<p>
  <style>
table, th, td {
    border: 1px solid green;
}th, td {
    padding: 5px;
}
</style>
  <table style="width:80%; margin: auto; border:"" %>
    <tr>
  <th>Name:</th>
  <th>Title:</th>
  <th>Proposal:</th>
</tr>
<tr>
  <td><%= @topic.name %></td>
  <td><%= @topic.title %></td>
  <td> <%= @topic.proposal %></td>
</table>

<h1 style="color:green;">Votes to date</h1>


<table style= "width:80; margin: auto;"%>
<tr>
    <% Topic.listings.each do |listing| %>
      <th><%= listing %></th>
    <% end %>
  </tr>
   <tr>
     <td><%= @topic.Angie_vote%></td>
     <td><%= @topic.Clare_vote%></td>
     <td><%= @topic.Debbie_vote%></td>
     <td><%= @topic.Helen_vote%></td>
     <td><%= @topic.Sarah_vote%></td>
     <td><%= @topic.Vicky_vote%></td>
     <td><%= @topic.David_vote%></td>
     <td><%= @topic.Mike_vote%></td>
     <td><%= @topic.Howard_vote%></td>
    </tr>
</table>

<h1 style="color:green;">Comments to date</h1>
<%= render @topic.comments.reverse_order %>
<h1 style="color:red;" > Make comments</h1>
<%= render 'comments/form' %>